import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface VirtualTryOnRequest {
  personImageUrl: string;
  garmentImageUrl: string;
  category?: 'upper_body' | 'lower_body' | 'dresses';
}

// Fallback using Lovable AI (Nano Banana / Gemini)
async function tryOnWithLovableAI(
  personImageUrl: string,
  garmentImageUrl: string,
  category: string
): Promise<string> {
  const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
  if (!LOVABLE_API_KEY) {
    throw new Error('LOVABLE_API_KEY is not configured');
  }

  const categoryDescriptions: Record<string, string> = {
    'upper_body': 'upper body clothing (shirt, top, jacket, sweater)',
    'lower_body': 'lower body clothing (pants, shorts, skirt)',
    'dresses': 'full dress or one-piece outfit'
  };

  const categoryDesc = categoryDescriptions[category] || categoryDescriptions['upper_body'];

  const prompt = `You are a virtual try-on expert. I'm showing you two images:
1. First image: A person who wants to try on clothes
2. Second image: A garment (${categoryDesc})

Your task: Generate a realistic image of the SAME person from image 1, but wearing the garment from image 2. 
- Preserve the person's face, body shape, pose, and background exactly
- Replace their current ${category === 'upper_body' ? 'top/shirt' : category === 'lower_body' ? 'pants/bottoms' : 'outfit'} with the garment shown
- Make sure the garment fits naturally on the person's body
- Keep lighting and shadows consistent
- The result should look like a professional fashion photo`;

  console.log('Using Lovable AI fallback for virtual try-on');

  const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${LOVABLE_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'google/gemini-2.5-flash-image-preview',
      messages: [
        {
          role: 'user',
          content: [
            { type: 'text', text: prompt },
            { type: 'image_url', image_url: { url: personImageUrl } },
            { type: 'image_url', image_url: { url: garmentImageUrl } }
          ]
        }
      ],
      modalities: ['image', 'text']
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('Lovable AI error:', response.status, errorText);
    
    if (response.status === 429) {
      throw new Error('Rate limit exceeded. Please try again later.');
    }
    if (response.status === 402) {
      throw new Error('AI credits exhausted. Please add funds to your workspace.');
    }
    throw new Error(`Lovable AI error: ${response.status}`);
  }

  const data = await response.json();
  const generatedImage = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;

  if (!generatedImage) {
    throw new Error('No image generated by Lovable AI');
  }

  return generatedImage;
}

// Primary method using FAL.ai IDM-VTON
async function tryOnWithFal(
  personImageUrl: string,
  garmentImageUrl: string,
  category: string
): Promise<string> {
  const FAL_API_KEY = Deno.env.get('FAL_API_KEY');
  if (!FAL_API_KEY) {
    throw new Error('FAL_API_KEY is not configured');
  }

  const response = await fetch('https://queue.fal.run/fal-ai/idm-vton', {
    method: 'POST',
    headers: {
      'Authorization': `Key ${FAL_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      human_image_url: personImageUrl,
      garment_image_url: garmentImageUrl,
      category,
      adjust_hands: true,
      auto_mask: true,
      auto_crop: true,
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('FAL API error:', response.status, errorText);
    
    // Check if it's a balance/account issue - trigger fallback
    if (response.status === 403 || errorText.includes('Exhausted balance') || errorText.includes('locked')) {
      throw new Error('FAL_EXHAUSTED');
    }
    throw new Error(`FAL API error: ${response.status}`);
  }

  const submitData = await response.json();
  const requestId = submitData.request_id;

  console.log(`FAL job submitted, request_id: ${requestId}`);

  // Poll for completion
  for (let i = 0; i < 60; i++) {
    await new Promise(resolve => setTimeout(resolve, 3000));

    const resultResponse = await fetch(`https://queue.fal.run/fal-ai/idm-vton/requests/${requestId}`, {
      headers: {
        'Authorization': `Key ${FAL_API_KEY}`,
      },
    });

    if (resultResponse.ok) {
      const data = await resultResponse.json();
      if (data.image?.url || data.images?.[0]?.url) {
        return data.image?.url || data.images?.[0]?.url;
      }
    }
  }

  throw new Error('FAL generation timed out');
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const params: VirtualTryOnRequest = await req.json();
    const { personImageUrl, garmentImageUrl, category = 'upper_body' } = params;

    if (!personImageUrl || !garmentImageUrl) {
      throw new Error('personImageUrl and garmentImageUrl are required');
    }

    console.log(`Virtual try-on: category=${category}`);

    let resultImageUrl: string;

    // Try FAL.ai first, fallback to Lovable AI
    try {
      resultImageUrl = await tryOnWithFal(personImageUrl, garmentImageUrl, category);
      console.log('Virtual try-on completed with FAL.ai');
    } catch (falError) {
      const errorMessage = falError instanceof Error ? falError.message : '';
      
      // If FAL.ai fails due to balance/account issues, use Lovable AI fallback
      if (errorMessage === 'FAL_EXHAUSTED' || errorMessage.includes('403')) {
        console.log('FAL.ai unavailable, using Lovable AI fallback...');
        resultImageUrl = await tryOnWithLovableAI(personImageUrl, garmentImageUrl, category);
        console.log('Virtual try-on completed with Lovable AI fallback');
      } else {
        throw falError;
      }
    }

    return new Response(
      JSON.stringify({ imageUrl: resultImageUrl }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in virtual try-on:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});