-- Migration: Add generations bucket for AI-generated content
-- This bucket stores images and videos generated by Imagen 4 and Veo 3

-- Create storage bucket for AI generations
INSERT INTO storage.buckets (id, name, public) 
VALUES ('generations', 'generations', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for generations bucket
-- Allow anyone to view generated content (public bucket)
CREATE POLICY "Anyone can view generations" 
ON storage.objects FOR SELECT 
USING (bucket_id = 'generations');

-- Allow authenticated users to upload to their own folder
CREATE POLICY "Users can upload to generations bucket" 
ON storage.objects FOR INSERT 
WITH CHECK (
  bucket_id = 'generations' 
  AND auth.uid()::text = (storage.foldername(name))[1]
);

-- Allow service role to upload (for Edge Functions)
CREATE POLICY "Service role can upload to generations" 
ON storage.objects FOR INSERT 
WITH CHECK (
  bucket_id = 'generations'
  AND auth.role() = 'service_role'
);

-- Allow users to delete their own generations
CREATE POLICY "Users can delete own generations" 
ON storage.objects FOR DELETE 
USING (
  bucket_id = 'generations' 
  AND auth.uid()::text = (storage.foldername(name))[1]
);

-- Add video_generations table to track video generation operations
CREATE TABLE IF NOT EXISTS public.video_generations (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  prompt TEXT NOT NULL,
  video_url TEXT,
  thumbnail_url TEXT,
  status TEXT NOT NULL DEFAULT 'pending', -- pending, processing, completed, failed
  duration_seconds INTEGER DEFAULT 5,
  aspect_ratio TEXT DEFAULT '16:9',
  operation_name TEXT, -- Gemini operation ID for polling
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  completed_at TIMESTAMP WITH TIME ZONE
);

-- Enable RLS on video_generations
ALTER TABLE public.video_generations ENABLE ROW LEVEL SECURITY;

-- Video generations policies
CREATE POLICY "Users can view own video generations" 
ON public.video_generations FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create own video generations" 
ON public.video_generations FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own video generations" 
ON public.video_generations FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own video generations" 
ON public.video_generations FOR DELETE USING (auth.uid() = user_id);

-- Add generation_type to track tool used
ALTER TABLE public.creations 
ADD COLUMN IF NOT EXISTS tool_type TEXT DEFAULT 'text2img';

-- Add media_type column to creations for videos
ALTER TABLE public.creations 
ADD COLUMN IF NOT EXISTS media_type TEXT DEFAULT 'image' CHECK (media_type IN ('image', 'video'));

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_creations_user_id ON public.creations(user_id);
CREATE INDEX IF NOT EXISTS idx_creations_tool_type ON public.creations(tool_type);
CREATE INDEX IF NOT EXISTS idx_video_generations_user_id ON public.video_generations(user_id);
CREATE INDEX IF NOT EXISTS idx_video_generations_status ON public.video_generations(status);
